#### BASE CONFIG ####
baseURL = "https://magnoblog.netlify.app"
languageCode = "es"
title = "Magno Blog"
enableEmoji = true
enableGitInfo = true

[minify]
minifyOutput = true

#### BASE CONTENT CONFIG ####

[params]
# Footer and about (home.html)
author.name = "Magno El Magnífico"

# Blog logo (start:home.html), header, and icon on the tab
logo = "/logo.svg"

# Github repo link
footer_content = """
### Magno blog

¿Alguna mejora, comentario o sugerencia?

Abre un [Issue] en el [repositorio] del blog.

[repositorio]: https://github.com/MagnoElMagnifico/blog
[Issue]: https://github.com/MagnoElMagnifico/blog/issues
"""

#### MARKDOWN CONFIG ####

[markup.goldmark]
extensions.extras.mark.enable = true
extensions.extras.insert.enable = true

# Allow HTML in md files
[markup.goldmark.renderer]
unsafe = true

# Allow adding classes and ids to markdown elements with {.class #id}
[markup.goldmark.parser.attribute]
block = true
title = true

#### HIGHLIGHT CONFIG ####

[markup.highlight]
# https://xyproto.github.io/splash/docs/all.html
# "dracula", "fruity", "paraiso-dark", "rrt", "solarized-dark256", "vim"
style = "dracula"

tabWidth = 4
anchorLineNos = true # Create links for each line of code
guessSyntax = true

lineNos = true
lineNumbersInTable = false

[markup.tableOfContents]
startLevel = 0
endLevel = 3
ordered = true

