#### BASE CONFIG ####
baseURL = "https://magnoblog.netlify.app"
languageCode = "es"
title = "Magno Blog"
enableEmoji = true
enableGitInfo = true

[minify]
minifyOutput = true

#### BASE CONTENT CONFIG ####

[params]
# Footer and about (home.html)
author.name = "Magno El Magnífico"

# Blog logo (start:home.html), header, and icon on the tab
logo = "/logo.svg"

# Github repo link
footer_content = """
### Magno blog

¿Alguna mejora, comentario o sugerencia?

Abre un [Issue] en el [repositorio] del blog.

[repositorio]: https://github.com/MagnoElMagnifico/blog
[Issue]: https://github.com/MagnoElMagnifico/blog/issues
"""

#### MARKDOWN CONFIG ####

# Enable extensions
[markup.goldmark]
extensions.extras.mark.enable = true
extensions.extras.insert.enable = true

# Avoid scaping special markdown caracters
extensions.passthrough.enable = true
extensions.passthrough.delimiters.block = [["$$", "$$"]]
# TODO: This may cause problems when just using
# extensions.passthrough.delimiters.inline = [["$", "$"]]

# Allow HTML in md files for more flexibility
[markup.goldmark.renderer]
unsafe = true

# Allow adding classes and ids to markdown elements with {.class #id}
[markup.goldmark.parser.attribute]
block = true
title = true

#### HIGHLIGHT CONFIG ####

[markup.highlight]
# https://swapoff.org/chroma/playground/
style = "onedark"

tabWidth = 4
anchorLineNos = true # Create links for each line of code
guessSyntax = true

lineNos = false
lineNumbersInTable = false

[markup.tableOfContents]
startLevel = 0
endLevel = 3
ordered = true

